### ISSUE TITLE
I don't like this repo name

### ISSUE THREAD

**Issue by jsmeldru** [hal7df/further-suggestions#1]
# yoloswag2014 would have been a better name.

![usa freckles gymnast olympics 2012 mckayla maroney](https://f.cloud.github.com/assets/6330483/1883536/71ebfff8-7987-11e3-9640-5280b2b0044d.jpg)

**Comment by jsmeldru** [comment]
Still don't.

**Comment by hal7df** [comment]
Much too late to change it, Jay :P
